Share session
HabitatMap/AircastingAndroid pull request #100
Opened 2020-12-28 15:33 UTC by michalrazny2

I made pull request but there is much to do on this branch.

TODO:
- [] buttons in share_session_bottom_sheet.xml styles are not correct (same as in edit_session_bottom_sheet.xml),
- [] I am not sure if we are supposed to choose only one stream for now (layout suggests it),
- [] handling api call ( /api/sessions/export_by_uuid.json endpoint??)- I don't understand how it works yet

2020-12-31 10:39 UTC, mturnau commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/ShareSessionBottomSheet.kt
> +            emailInput?.setText("")
I think this behaviour should not be here. When you click the share file button, a request is sent. You should pass there a success callback (a toast message & closing the bottom sheet and the actions menu). On failure, it should not close the form but show a toast with an error message. You can do it similarly to what we did in edit session.

2020-12-31 10:39 UTC, mturnau commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/SessionsController.kt
> +    ShareSessionBottomSheet.Listener{
formatting

2020-12-31 10:39 UTC, mturnau commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/ShareSessionBottomSheet.kt
> +        context?.startActivity(chooser)
hm, not sure whether this behaviour should not be rather in controller (it's starting new "activity").

2020-12-31 10:39 UTC, mturnau commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/ShareSessionBottomSheet.kt
> +        val chooser = Intent.createChooser(sendIntent, "Share link")
string should be in strings

2020-12-31 10:39 UTC, mturnau commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/dormant/MobileDormantController.kt
> +
extra lines

2021-01-07 12:20 UTC, lesniakania requested changes

2021-01-07 12:20 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/lib/ShareHelper.kt
> +        private val SHARE_TEXT = "Here I send you link to my session\n"
It could be in `strings.xml` - you can retrieve it then with `context.getString(id)`. You need to pass context to the `shareLink` method to do this.

2021-01-07 12:20 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/lib/ShareHelper.kt
> +            val sessionLink: String = session.urlLocation.toString() + SENSOR_PARAM + selectedSensorName
this is nitpicking, but I'd write it like that:
```kotlin
val sessionLink = "${session.urlLocation}$?{SENSOR_PARAM}=${selectedSensorName}"
```

this assumes that `SENSOR_PARAM` looks like that:

```kotlin
private val SENSOR_PARAM = "sensor_name"
```

2021-01-07 12:20 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/networking/services/ExportSessionService.kt
> +                }else{
nitpicking again :] - missing spaces ;]

2021-01-07 12:20 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/networking/services/ExportSessionService.kt
> +                errorHandler.showError(context.getString(R.string.errors_network_required_edit)) //todo: ^^
I think it would be better to create your own `SessionExportFailedError` or something like that and define error message there - see `exceptions.kt` file

2021-01-07 12:20 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/SessionsController.kt
> +    private fun shareLinkPressed(session: Session, chosenSensor: String){
maybe it would be better to name it more from what it does - like `openShareIntentChooser` or something

2021-01-07 12:20 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/ShareSessionBottomSheet.kt
> +            val radioButton = RadioButton(context)
I'd extract all of the lines inside `forEach` to a separate method

2021-01-07 12:20 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/sensor/SessionManager.kt
> +            Toast.makeText(mContext, "Exported sessions will be emailed within minutes. The email may end up in your spam folder.", Toast.LENGTH_LONG).show()
this string should be in `strings.xml`

2021-01-12 11:27 UTC, closed without merging