Smaller map graph follow unfollow buttons
HabitatMap/AircastingAndroid pull request #146
Opened 2021-02-03 18:33 UTC by yzmopolis

Important changes:

- I've changed paddings and dimens for `follow`, `unfollow`, `map`, `graphs` buttons
- I've added containers for buttons
- I used TouchDelegate to keep the touchable area the same as earlier (container - parent is touchable)

<img width="299" alt="Screenshot 2021-02-03 at 19 18 39" src="https://user-images.githubusercontent.com/23139274/106791448-34dbb780-6655-11eb-993c-98c54df5400e.png">

AC:

- [ ] it matches proto: https://projects.invisionapp.com/share/DCWT9W6BUE7#/screens/414476845
- [ ] touchable area is the same

[TouchDelegate docs](https://developer.android.com/reference/android/view/TouchDelegate.html)

[ticket](https://trello.com/c/3fb7fnUc/1070-cards-map-graph-follow-buttons-should-match-the-proto)

2021-02-04 08:38 UTC, lesniakania requested changes

2021-02-04 08:38 UTC, lesniakania commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_top_5">5dp</dimen>
when we started implementing layouts with @mturnau we used similar constants, but at some point, we agreed (I think after reading some article, but I don't remember exactly) that when we have a situation that we just need to use specific dimensions, we are just using it in the XML as it is, without adding it to the dimens file.
I guess it was about readability and not making too many and a bit artificial dimens.

2021-02-04 08:38 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/SessionViewMvcImpl.kt
> +        mFollowTouchableArea = findViewById(R.id.follow_container)
I wanted to comment that we agreed on using "the new magic syntax" as I was referring to kotlin synthetics syntax, but I wanted to google it and look what I just found....:
https://medium.com/better-programming/why-are-kotlin-synthetics-deprecated-and-what-are-the-alternatives-5c2b087dda1c /cc @michalrazny2 ....
I guess we should be moving to the data binding syntax, but let's not worry about this now, maybe just when you create any new views, please use that.

2021-02-04 08:38 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/SessionViewMvcImpl.kt
> +    private var mGraphTouchableArea: LinearLayout
I'm a bit concerned with these linear layouts - too many layouts (can cause performance problems)[https://stackoverflow.com/a/15405309] and we have lots of sessions on the fixed and dormant tabs to display.
I'd try removing them and in the `expandViewHitArea` use something like this:
```kotlin
childRect.top -= TOUCHABLE_PADDING;
childRect.left -= TOUCHABLE_PADDING;
childRect.right += TOUCHABLE_PADDING;
childRect.bottom += TOUCHABLE_PADDING;
```

where `TOUCHABLE_PADDING` would be some constant defined in this class.
you can check more examples [here](https://www.programcreek.com/java-api-examples/?api=android.view.TouchDelegate).

2021-02-04 13:45 UTC, yzmopolis commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/SessionViewMvcImpl.kt
> +    private var mGraphTouchableArea: LinearLayout
Thanks for this comment, I'll remember it :)

2021-02-04 13:46 UTC, yzmopolis commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_top_5">5dp</dimen>
@lesniakania of course, I didn't know, I'll follow your approach 🐾

2021-02-05 09:19 UTC, lesniakania approved these changes

2021-02-05 09:19 UTC, merged