Onboarding
HabitatMap/AircastingAndroid pull request #169
Opened 2021-02-16 15:15 UTC by michalrazny2

https://trello.com/c/Dq83XRSJ/831-onboarding

2021-02-18 12:34 UTC, mturnau commented on app/src/main/res/layout/onboarding_page_1.xml
> +    <ImageView
This image is supposed to take full width. I'm afraid the easiest way would be to remove paddings from onboarding_activity and add them to all elements individually (then you can have 0 paddings on that image). Playing with negative paddings is rather the last resort. Maybe there is some other way but couldn't find it easily.

2021-02-18 12:34 UTC, mturnau commented on app/src/main/java/io/lunarlogic/aircasting/screens/onboarding/OnboardingWizardNavigator.kt
> +        val fragment = OnboardingPage3Fragment()
not sure in which place but when everything is green, the progress bar color should be green as well. There are several ways to do it. A hint would be (maybe) that primaryColor is used there in XML so maybe you could apply style overlay only in that view to change primary color?

2021-02-18 12:34 UTC, mturnau commented on app/src/main/res/layout/activity_create_account.xml
> +    android:background="@drawable/dashboard_background">
is this a monochromatic rainbow thingy? If so, note that in create account it should be blue, not green!

2021-02-18 12:34 UTC, mturnau commented on app/src/main/res/layout/activity_create_account.xml
> +    android:background="@drawable/dashboard_background">
ah and also it is green on the dashboard.. should be blue also there

2021-02-18 12:34 UTC, mturnau commented on app/src/main/res/layout/onboarding_page_2.xml
> +        android:layout_height="wrap_content"
It is super important that when you want to constraint this image to guidelines, you need to set height to 0dp (match constraints) and width to wrap_content. Otherwise it won't work as intended. I suggest you change it in all screens with picture and text and check on different sizes of screen. PRO TIP: Using an emulator is not needed in fact. Go to the xml file, select design view and you can select the device on the top left. If you scroll to the bottom of the menu you have "generic phones and tablets" and you have all sizes, like 3,2'' as well.

2021-02-22 09:34 UTC, lesniakania requested changes

2021-02-22 09:34 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/create_account/CreateAccountViewMvcImpl.kt
> +            progressBar?.progress = 75   // todo: hardcoded for now <?>
yeah I guess hardcoded is fine, but maybe just in the XML directly?

2021-02-22 09:34 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/create_account/CreateAccountViewMvcImpl.kt
> +            progressBar?.progress = 75   // todo: hardcoded for now <?>
and sign in view also has progress bar

2021-02-22 09:34 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/onboarding/OnboardingController.kt
> +): OnboardingPage1ViewMvc.Listener,
I'd name those steps more verbosly - e.g `OnboardingGetStarted`, `OnboardingHowsTheAir` etc

2021-02-22 09:34 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/onboarding/OnboardingWizardNavigator.kt
> +class OnboardingWizardNavigator(
as agreed on the call, add base wizard on this branch

2021-02-22 09:36 UTC, lesniakania commented
fixe tests by setting `shouldOnboardingAppear` setting and add additional test for onboarding flow

2021-02-22 10:06 UTC, lesniakania commented on app/src/main/res/layout/activity_create_account.xml
> +    android:background="@drawable/dashboard_background">
and should be more transparent

2021-02-22 11:33 UTC, michalrazny2 commented on app/src/main/res/layout/onboarding_page_1.xml
> +    <ImageView
isn't it enough if I just set width as "match_parent" ?

2021-02-22 14:52 UTC, michalrazny2 commented on app/src/main/res/layout/onboarding_page_1.xml
> +    <ImageView
the problem is I have no paddings in activity_onboarding now :|

2021-02-23 13:59 UTC, lesniakania approved these changes

2021-02-23 14:12 UTC, merged