Delete streams or session confirmation dialog
HabitatMap/AircastingAndroid pull request #177
Opened 2021-02-23 15:37 UTC by yzmopolis

2021-02-23 15:48 UTC, yzmopolis commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/SessionsController.kt
> +        }
I couldn't use setButtonPositive etc methods, because there is no option to have these default buttons customized. When we use a custom layout with our buttons it's only possible to add listeners to them. I don't like it, but well... 🦝

2021-02-24 08:51 UTC, lesniakania requested changes

2021-02-24 08:51 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/SessionsController.kt
> +        }
I think it might be better to do the same as in `NetworkPasswordDialog` - do a separate class for that and put this logic there, with the listener.

2021-02-24 08:51 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/SessionsController.kt
> +        header.text = this.context?.getString(R.string.are_you_sure)
I think you can move it to the XML?

2021-02-25 10:32 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/ConfirmationDeleteSessionDialog.kt
> +        function()
sorry, last neat picking - can you change a name `function` to `okCallback`?

2021-02-25 10:33 UTC, lesniakania approved these changes

2021-02-25 10:35 UTC, yzmopolis commented on app/src/main/java/io/lunarlogic/aircasting/screens/dashboard/ConfirmationDeleteSessionDialog.kt
> +        function()
of course! 🐈

2021-02-25 13:29 UTC, merged