Fix progress bar to show correct progress
HabitatMap/AircastingAndroid pull request #194
Opened 2021-03-03 11:42 UTC by michalrazny2

https://trello.com/c/29pfMpDY/1154-fix-progress-bar-to-show-correct-progress

2021-03-03 11:56 UTC, mturnau commented on app/src/main/java/io/lunarlogic/aircasting/screens/common/BaseWizardNavigator.kt
> +    open var MAX_PROGRESS = 40
this is not really max progress because it can be higher ;) I'd name it `DEFAULT_MAX_PROGRESS` or similar

2021-03-03 11:56 UTC, mturnau commented on app/src/main/java/io/lunarlogic/aircasting/screens/new_session/NewSessionController.kt
> +            wizardNavigator.MAX_PROGRESS += 10
typically we use capital letters for constants. Technically, it's not a const but var but when you use it like a var (increase) it should not be named with capital letters. You can have two things: a const to keep a default max and a var to keep the current max value

2021-03-05 07:14 UTC, lesniakania requested changes

2021-03-05 07:14 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/common/BaseWizardNavigator.kt
> +    val progressBarCounter = ProgressBarCounter(4) // we got 3 basic steps in the flow (progress bar should have 1 more to look better)
I'd move this `4` along with a comment and set it as a constant in `ProgressBarCounter` and use it in the constructor as default

2021-03-05 07:14 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/new_session/NewSessionController.kt
> +            wizardNavigator.progressBarCounter.increaseMaxProgress(1) // 1 additional step in flow
I'd make `increaseMaxProgress` method in the wizard navigator, use there `progressBarCounter.increaseMaxProgress` and set `1` as default

2021-03-05 07:14 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/settings/clear_sd_card/ClearSDCardController.kt
> +    private fun setupProgressBarMax() {
and also seeing we would need to have the same things here as in `NewSessionController`, maybe we should move whole this method to the wizard class and pass `areLocationServicesOn` and other booleans as args?

2021-03-05 11:53 UTC, lesniakania commented on app/src/main/java/io/lunarlogic/aircasting/screens/create_account/CreateAccountViewMvcImpl.kt
> -            settings.onboardingAccepted()
I guess this was temp thing ; ]?

2021-03-05 12:08 UTC, merged