Follow session card and search screen
HabitatMap/AircastingAndroid pull request #429
Opened 2022-04-21 10:02 UTC by xameYeoh

These are layouts for Let's begin screen and Search sessions screen

2022-04-21 11:28 UTC, LinX64 commented on app/src/main/res/layout/search_fixed_sessions.xml
> +
Needs a reformat code + remove the extra spaces -> `Control`+`option`+`L`

2022-04-21 11:31 UTC, LinX64 commented on app/src/main/res/layout/search_fixed_sessions.xml
> +    <TextView
You'll probably need to change the name. i.e, adding a `fragment` or something similar + maybe adding the App bar at the top, instead of adding `TextView` above it.

2022-04-21 11:32 UTC, LinX64 commented on app/src/main/res/layout/search_fixed_sessions.xml
> +                android:id="@+id/particulate_matter_radio_button"
You're still using the radio button IDs for chips!

2022-04-21 11:45 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/lib/extensions.kt
> +fun setupAppBar(activity: BaseActivity, toolbar: androidx.appcompat.widget.Toolbar) {
Try to import the `Toolbar` as `androidx.appcompat.widget.Toolbar` also I think it needs a reformat code + `control` + `option` + `o` for the imports.

2022-04-21 11:47 UTC, LinX64 requested changes
I left a few comments on the changes you made.

2022-04-21 11:50 UTC, xameYeoh commented on app/src/main/res/layout/search_fixed_sessions.xml
> +                android:id="@+id/particulate_matter_radio_button"
Oops

2022-04-22 17:29 UTC, LinX64 commented
![](https://github.trello.services/images/mini-trello-icon.png) [let's begin > follow session: update subtext to read "search & follow fixed sessions"](https://trello.com/c/e2r0jFN8/1475-lets-begin-follow-session-update-subtext-to-read-search-follow-fixed-sessions)

2022-05-01 17:19 UTC, LinX64 commented
Merged in https://github.com/HabitatMap/AircastingAndroid/pull/432. Closing the PR.

2022-05-01 17:19 UTC, closed without merging