Connecting two sessions kinds
HabitatMap/AircastingAndroid pull request #452
Opened 2022-05-31 14:15 UTC by xameYeoh

2022-06-02 09:27 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedBottomSheet.kt
> +            Thread {
Don't do the DB operations here, this violates the MVVM roles of separating View and using the ViewModel.

You can use `Dispatchers.IO` for that purpose in the `ViewModel`.

2022-06-02 09:44 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/data/local/dao/ExtSessionDao.kt
> +    fun insert(extSession: ExtSessionsDBObject)
After those changes from above, this will need to make it `suspend`.

2022-06-02 09:44 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/data/local/dao/ExtSessionDao.kt
> +    fun delete(extSession: ExtSessionsDBObject)
Also for this: `suspend fun ..`

2022-06-02 09:50 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/data/local/dao/ExtSessionDao.kt
> +    fun insert(extSession: ExtSessionsDBObject)
I thought you did not want to add the coroutines to Room at the end? We don't have them with previous queries

2022-06-02 09:52 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/search/SearchFixedBottomSheet.kt
> +            Thread {
I created this [pr](https://github.com/HabitatMap/AircastingAndroid/pull/455) to put logic related to this part there

2022-06-02 09:54 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/data/local/dao/ExtSessionDao.kt
> +    fun insert(extSession: ExtSessionsDBObject)
We're using MVVM for this feature and after this, we'll need to use it even more.

I was suspicious about the `LiveData` actually and not the `Coroutines` - Using Coroutines has no harm.

2022-06-02 09:56 UTC, LinX64 requested changes
Added a few comments.

2022-06-02 09:58 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/data/local/dao/ExtSessionDao.kt
> +    fun insert(extSession: ExtSessionsDBObject)
Okay, will look into that 👌

2022-06-02 11:03 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/data/local/dao/ExtSessionDao.kt
> +    fun insert(extSession: ExtSessionsDBObject)
We decided to keep the methods non suspend, as it prevents some of them to return LiveData, and other parts of the app are heavily dependent on that. Besides, other queries are not using suspend, so the consistency stays

2022-06-03 09:28 UTC, LinX64 approved these changes

2022-06-03 09:29 UTC, LinX64 commented
Looks cool now, feel free to merge it when you think it is ready.

2022-06-03 14:34 UTC, merged