Chart on the BottomSheet
HabitatMap/AircastingAndroid pull request #473
Opened 2022-06-15 10:26 UTC by LinX64

2022-06-15 17:15 UTC, LinX64 commented
![](https://github.trello.services/images/mini-trello-icon.png) [5. [Session] Chart](https://trello.com/c/3lmXkMuQ/1536-5-session-chart)

2022-06-21 07:44 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionPresenter.kt
> +        if (session.tab == SessionsTab.FOLLOWING || session.tab == SessionsTab.MOBILE_ACTIVE && session.isExternal) {
Should it not be OR session.isExternal ?

2022-06-21 07:56 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/data/model/SensorThreshold.kt
> +        )
I did not see this getter used in this pr, but I presume that's for the SessionPresenter, right? I think this is a good idea to be able to get all the thresholds from the session in some sort of single structure. But I would use the SensorThreshold as a return value from here - as this is precisely what SessionPresenter needs to be constructed. So we might as well have a getter for SensorThreshold getter from these thresholds, instead of a list

2022-06-21 07:58 UTC, xameYeoh requested changes
I've highlighted the parts that I think require some refactoring

2022-06-21 10:19 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/data/model/SensorThreshold.kt
> +        )
Good point! I don't think it is for the `SessionPresenter` as I saw it was being used for the `Measurement` and for getting the levels and showing it with the specific colors. As we discussed, the `SessionPresenter` already has those parameters in its own constructor so I guess that we can use the same approach I used without any problems.

2022-06-21 10:24 UTC, LinX64 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Improvements](https://trello.com/c/etqvBVnj/1565-improvements)

2022-06-21 12:09 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/data/model/SensorThreshold.kt
> +        )
Sorry, I confused it a bit - I thought this was in a MeasurementStream class. I guess it would be nice for this class to provide it's thresholds in a bundle as SensorThreshold, but if all other parts of the app construct it the same way as you do for the SessionPresenter, I guess we better have it unified

2022-06-21 12:31 UTC, merged