Set Pm2.5 as default
HabitatMap/AircastingAndroid pull request #523
Opened 2022-07-07 13:06 UTC by LinX64

2022-07-07 15:08 UTC, LinX64 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make Pm2.5 default for both external sessions and internal](https://trello.com/c/Q2W3DDsQ/1610-make-pm25-default-for-both-external-sessions-and-internal)

2022-07-10 08:55 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/data/api/util/StringConstants.kt
> +
As far as I got it, the streamsSortedByDetailedType() works with AirBeamSensorName enum, which has detailedType strings in it, including "PM2.5". I would use the one from there, instead of creating another one, so that it will be from one source

2022-07-10 08:55 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/data/api/util/StringConstants.kt
> +
And in this case we can rename the enum from AirBeamSensorName to just SensorName, as we work not only with airbeams now

2022-07-10 08:58 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionPresenter.kt
> +            return session?.streamsSortedByDetailedType()?.find { it.detailedType == StringConstants.pmTwoPointFive }
So here I would have SensorName.PM2_5.detailedType from enum

2022-07-10 09:03 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/data/api/util/StringConstants.kt
> +
Another idea might be, if we want to keep all the constants in files, replace the strings in the enum with StringConstants.pmTwoPointFive so that we would have:
```
enum class SensorName(val detailedType: String) {
        F(StringConstants.F),
        PM(StringConstants.PM),
        // and so on
```
But in the defaultStream() method I would still use the enum value like SensorName.PM2_5.detailedType

2022-07-10 09:04 UTC, xameYeoh requested changes
I've left some ideas on refactoring

2022-07-10 11:16 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/data/api/util/StringConstants.kt
> +
Didn't notice that enum class, thanks for mentioning it!

2022-07-10 11:17 UTC, merged

2022-07-10 11:31 UTC, xameYeoh commented
Looks super cool! 💪