Rebinding updated sessions only
HabitatMap/AircastingAndroid pull request #564
Opened 2022-07-22 12:34 UTC by xameYeoh

This is a final pr for refactoring the recycler - it includes rebinding individually only those sessions that were changed/inserted/deleted when observer gets notified

2022-07-26 09:43 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/data/model/observers/SessionsObserver.kt
> +    enum class ModificationType {
This enum class could go somewhere else. Let's separate it for the sake of Clean Architecture and Separation of Concerns.

2022-07-26 09:46 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/data/model/observers/SessionsObserver.kt
> +            if (anySensorThresholdChanged(sensorThresholds)) updateSensorThresholds(sensorThresholds)
Couldn't you use when in here?

```
when {
                anySensorThresholdChanged(sensorThresholds) -> updateSensorThresholds(
                    sensorThresholds
                )
                anySessionChanged(sessions) -> onSessionsChanged(coroutineScope, sessions)
            }

2022-07-26 11:54 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +                val success = replacePresenter(session)
Shouldn't we add the `success` variable beside the other variables? Like after the `position` val.

2022-07-26 12:13 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +                Session(dbSessionWithMeasurements)
We're using `let` to avoid nullability of the `dbSessionWithMeasurements` variable and then again you're passing the same variable to the `Session` inside the `let` scope. Don't make the same mistake as they did. Either pass `it`, or set a name for the lambda, and then pass it to `Session`;

```
 return@withContext dbSessionWithMeasurements?.let { Session(it) }
```

And/or:

```
 return@withContext dbSessionWithMeasurements?.let { dbSession ->
                Session(dbSession)
            }
```

2022-07-26 12:25 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/new_session/confirmation/ConfirmationController.kt
> +        //context?.hideKeyboard()
I think I reverted this back. So maybe you can use it as well because the relevant ext function should be already there.

2022-07-26 12:30 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/session_view/measurement_table_container/MeasurementsTableContainer.kt
> +    fun makeCollapsed(sessionPresenter: SessionPresenter? = mSessionPresenter, displayValues: Boolean = true) {
You are already passing the `mSessionPresenter` in the `SessionViewMvcImpl` where its  being called only from this class. Will we really need to assign the `mSessionPresenter` in this class too?

2022-07-26 12:31 UTC, LinX64 requested changes
I left a few comments regarding some changes in this PR. Some of them are important to look and some of them are not.

2022-07-26 12:33 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/data/model/observers/SessionsObserver.kt
> +            if (anySensorThresholdChanged(sensorThresholds)) updateSensorThresholds(sensorThresholds)
As far as I got it, when does not execute sequentially like in Java, so only one command will execute in this case. And these need to be executed both if both conditions are true

2022-07-26 12:36 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +                val success = replacePresenter(session)
Not sure what you mean here, like that? :
```
val position = mSessionUUIDS.indexOf(session.uuid)
val success = replacePresenter(session)
            if (found(position)) {
                replaceSession(position, session)
```
The replacing of presenter only makes sense if the UUID was found at the given position

2022-07-26 12:38 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +                Session(dbSessionWithMeasurements)
If this is still nullable in the lambda, shouldn't the compiler notify in such case?

2022-07-26 12:45 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/data/model/observers/SessionsObserver.kt
> +            if (anySensorThresholdChanged(sensorThresholds)) updateSensorThresholds(sensorThresholds)
I see. "if both conditions are true" - then why not `if(firstCondition && second)`? Could be written simpler right?

2022-07-26 12:51 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/data/model/observers/SessionsObserver.kt
> +    enum class ModificationType {
I have thought about whether to put it and how to name it for a long time, and after some research, I've come to a conclusion that enums should belong to the place where they are used. In these case, the enum is utilised only in this class, so I figured that there would be no point to transfer it to some other place. Besides, when its name is accessed like: SessionsObserver.ModificationType to me it sounds logical and full, - so you can first guess that it is tied to the Observer and it describes the Modification Type that was made on a Session. 
If this will be transferred somewhere else, I think that all these connections will somehow be needed to be put in the name, and here it is achieved by putting it in the only class where it is used

2022-07-26 13:24 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/data/model/observers/SessionsObserver.kt
> +            if (anySensorThresholdChanged(sensorThresholds)) updateSensorThresholds(sensorThresholds)
No, not like that. Those are two separate events - when the thresholds change and when the session's data change. They happen irrespectively from each other.

2022-07-26 13:29 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/data/model/observers/SessionsObserver.kt
> +    enum class ModificationType {
This is true only if we'll be using this enum in this class and nowhere else. In this case, it makes sense to keep it there!

2022-07-26 13:38 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +                val success = replacePresenter(session)
I'm talking about this line: `val success = replacePresenter(session)` - I was wondering if it is possible to add this variable right after the first one one. If not, adding a space after this line `replaceSession(position, session)` will make it more understandable, what do you think?

2022-07-26 13:40 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +                Session(dbSessionWithMeasurements)
That was weird to me too! Not sure why its not notifying us but, the structure is pretty simple.

2022-07-26 13:44 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +                val success = replacePresenter(session)
Like that?
```
            val success: Boolean
            val position = mSessionUUIDS.indexOf(session.uuid)
            if (found(position)) {
                replaceSession(position, session)
                success = replacePresenter(session)
                if (success) notifyItemChanged(position)
            }
```

2022-07-26 14:27 UTC, LinX64 approved these changes

2022-07-28 10:17 UTC, closed without merging

2022-07-28 10:19 UTC, xameYeoh commented
The changes were transferred [here](https://github.com/HabitatMap/AircastingAndroid/pull/573) with better git history