Search and follow | Refactor
HabitatMap/AircastingAndroid pull request #584
Opened 2022-08-01 22:24 UTC by LinX64

2022-08-01 22:39 UTC, LinX64 commented
![](https://github.trello.services/images/mini-trello-icon.png) [When pressing back on map screen goes to dashboard](https://trello.com/c/giowUsLu/1685-when-pressing-back-on-map-screen-goes-to-dashboard)

2022-08-02 12:24 UTC, xameYeoh requested changes
The android back button (so not top arrow - but native android back button) still returns to the Dashboard instead of search screen

2022-08-03 09:53 UTC, LinX64 commented
It's solved in [this PR](https://github.com/HabitatMap/AircastingAndroid/pull/589).

2022-08-03 13:11 UTC, xameYeoh approved these changes

2022-08-03 13:11 UTC, merged