Add constraints, make top margin for loader on cards smaller for it t…
HabitatMap/AircastingAndroid pull request #643
Opened 2022-08-26 12:31 UTC by xameYeoh

…o not go too low

2022-08-26 13:29 UTC, LinX64 commented on app/src/main/res/layout/session_card.xml
> +            android:layout_marginTop="@dimen/keyline_6"
The top padding should be still reduced. I used `keyline_5` and it was looking much better.

2022-08-26 13:30 UTC, LinX64 requested changes
Left comment

2022-08-26 13:44 UTC, xameYeoh commented on app/src/main/res/layout/session_card.xml
> +            android:layout_marginTop="@dimen/keyline_6"
I've placed it now using constraints, without margin. I think that if the margin is used there will still be devices where it will be obscured (on my phone for example I don't have it obscured even keyline_8 is used 😮 )

2022-08-29 08:16 UTC, LinX64 commented on app/src/main/res/layout/session_card.xml
> -            android:layout_marginTop="@dimen/keyline_8"
Looks good with the new changes, however, this will cause an overlap which we will need to take care of it ASAP.

![alt text](https://i.imgur.com/8yJKNuH.png)

2022-08-29 08:17 UTC, LinX64 approved these changes

2022-08-29 11:42 UTC, merged