Sort sessions in recycler
HabitatMap/AircastingAndroid pull request #670
Opened 2022-09-09 10:08 UTC by xameYeoh

This changes the way how recycler's base Adapter holds data from using a combination of `HashMap with Presenters` and `List with UUIDs` to just one `SortedList with Presenters`. This enables to define different criteria on how the sessions cards will be sorted in each of the adapters by providing a SortedList.Callback to the list. 

The primary reason for using it was to always sort sessions on Fixed and Mobile Dormant tabs by their start time.

2022-09-09 14:21 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/reordering_following/ReorderingFollowingRecyclerAdapter.kt
> +        firstPresenter.session?.uuid?.let {
No need to use `let` when it is receiving a String for the first parameter. Check this:

```
private fun updateSessionsOrderInDatabase(
        firstPresenter: SessionPresenter,
        secondPresenter: SessionPresenter
    ) {
        val firstPresenterUUID = firstPresenter.session?.uuid.toString()
        val secondPresenterUUID = secondPresenter.session?.uuid.toString()

        mSessionsViewModel.updateOrder(firstPresenterUUID, firstPresenter.session?.order ?: 0)
        mSessionsViewModel.updateOrder(secondPresenterUUID, secondPresenter.session?.order ?: 0)
    }
```

2022-09-09 14:21 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/reordering_following/ReorderingFollowingRecyclerAdapter.kt
> +        firstPresenter.session?.uuid?.let {
It's much clear and understandable in this way, right?

2022-09-09 14:24 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/reordering_following/ReorderingFollowingRecyclerAdapter.kt
> +        mSessionPresenters.recalculatePositionOfItemAt(firstPosition)
And how about adding a space before this line to make it more understandable? Let's separate the variables from the others.

2022-09-09 14:50 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/reordering_following/ReorderingFollowingRecyclerAdapter.kt
> +        mSessionPresenters[position].session?.let { mSessionFollower.unfollow(it) }
You're only using `let` scope function for this `unfollow()` method, shouldn't we have something life this?

```
override fun onItemDismiss(position: Int) {
        val session = mSessionPresenters[position].session ?: return

        mSessionFollower.unfollow(session)
        mSessionPresenters.removeItemAt(position)
    }
```

2022-09-11 11:08 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
>      override fun getItemCount(): Int {
Since you refactored the adapter, I would have:

`override fun getItemCount() = mSessionPresenters.size()`

2022-09-11 11:10 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
>      private fun update(sessions: List<Session>?) {
Let's make it more clear by adding the `session` in the scope func: 

```
private fun update(sessions: List<Session>?) {
        sessions?.forEach { session -> update(session) }
    }
```

2022-09-11 11:10 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +                mSessionPresenters.updateItemAt(position, presenter)
A space before this line maybe?

2022-09-11 11:12 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +            notifyItemChanged(position)
Both show/hide loaders (almost) have the same structure; what about adding a space before `notifyItemChanged(position)` ?

2022-09-11 11:20 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +            return o2?.session?.startTime?.compareTo(o1?.session?.startTime) ?: 0
What is o1, o2? Shouldn't we have a specific name for it? Seems to be an autogenerated name.

Since it is comparing the session presenters, it could be `oldPresenter`, and `newPresenter`.

2022-09-11 11:22 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +        override fun areContentsTheSame(
How about this?

```
override fun areContentsTheSame(
            oldItem: SessionPresenter?,
            newItem: SessionPresenter?
        ) = newItem?.session?.hasChangedFrom(oldItem?.session) == false
```

2022-09-11 11:23 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +            return o2?.session?.startTime?.compareTo(o1?.session?.startTime) ?: 0
Also, it could be like this without defining the type as return:

```
 override fun compare(o1: SessionPresenter?, o2: SessionPresenter?) =
            o2?.session?.startTime?.compareTo(o1?.session?.startTime) ?: 0
```

2022-09-11 11:30 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/following/FollowingRecyclerAdapter.kt
> +    inner class FollowingModificationCallback : ModificationCallback() {
What about this ?

```
inner class FollowingModificationCallback : ModificationCallback() {
        override fun compare(o1: SessionPresenter?, o2: SessionPresenter?) =
            o1?.session?.order?.compareTo(o2?.session?.order ?: 0) ?: 0
    }
```

2022-09-11 11:33 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/viewmodel/SessionsViewModel.kt
>      }
There is an extra space after this line.

2022-09-11 11:46 UTC, LinX64 commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
>      protected fun reloadSessionFromDB(session: Session): Session {
How about doing a refactor and finishing this `runBlocking` topic once and for all?

```
protected fun reloadSessionFromDB(session: Session): Session {
        var reloadedSession: Session? = null

        runOnIOThread {
            val dbSessionWithMeasurements =
                mSessionsViewModel.reloadSessionWithMeasurements(session.uuid)
            reloadedSession = dbSessionWithMeasurements?.let { it1 -> Session(it1) }
        }

        return reloadedSession ?: session
    }
```

2022-09-11 11:47 UTC, LinX64 requested changes
I left some refactoring and changes comments.

2022-09-12 09:03 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/reordering_following/ReorderingFollowingRecyclerAdapter.kt
> +        firstPresenter.session?.uuid?.let {
Cool lifehack with the toString(), did not know it returns "null" string if the receiver is null

2022-09-12 09:20 UTC, xameYeoh commented on app/src/main/java/pl/llp/aircasting/ui/view/screens/dashboard/SessionsRecyclerAdapter.kt
> +            return o2?.session?.startTime?.compareTo(o1?.session?.startTime) ?: 0
Yeah, to be honest I like the autogenerated names, they are general. These are not about old and new, but about comparing one SessionPresenter to another (how they should be sorted). I've renamed it to `first` and `second`

2022-09-12 12:23 UTC, merged